service: serverless-webpack-example

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    includeModules: true
    keepOutputDirectory: true

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action: ['s3:GetObject']
      Resource: '*'

functions:
  timezones:
    handler: src/timeZones.handler
    events:
      - http:
          path: timezones
          method: post
